### ISSUE TITLE
Keyboards and portable keyboards do not work on Valkyrien Skies ships.

### ISSUE THREAD

**Issue by IAteMinecraft** [tom5454/Toms-Peripherals#20] opened 2024-08-24 06:50 UTC
When attempting to use a normal keyboard, it will flash "Keyboard open. Press ESC to close." once, and then the text disappears and then the keyboard doesn't do anything.

When attempting to use the portable keyboard, it will just say "Dongle out of range." when I am standing right next to the dongle on the Valkyrien skies ship.

I hope this gets fixed soon

**Comment by tom5454** [comment] 2024-08-24 12:38
Duplicate of #14

**Closed by tom5454** 2024-08-24 12:38 UTC
